name: Unlimited-Materials
version: 1.2
description: Unlimited Materials for MHM
author: Zubi
website: http://Zubi.fr
depend: [Spout]

main:  zubi.mhm.unlimitedmaterials.UnlimitedMaterials

commands:
  um:
    description: rebuild les blocs custom
    usage: /um rebuild [size]