name: Unlimited-Materials
version: 1.2
description: Unlimited Materials for MHM
author: Zubi
website: http://Zubi.fr
depend: [Spout]

main:  zubi.mhm.unlimitedmaterials.UnlimitedMaterials

commands:
   UnlimitedMaterials:
      description: inutile pour le moment
      usage: /um